
development:
  adapter: postgresql
  encoding: unicode
  database: hungrynames_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: hungrynames_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: hungrynames_production
  pool: 5
